exports.seed = async function (knex) {
  await knex("items").del();
  await knex("items").insert([
    {
      category_id: 1,
      name: "Geladeira",
      photo: "geladeira.png",
      input_name: "refrigerator",
      default_watts: 50.8,
      max_select_range: 5,
      flag_residents: false,
    },
    {
      category_id: 1,
      name: "Fogão por indução",
      photo: "cooktop.png",
      input_name: "cooktop",
      default_watts: 6000,
      max_select_range: 5,
      flag_residents: false,
    },
    {
      category_id: 1,
      name: "Forno elétrico",
      photo: "forno_eletrico.png",
      input_name: "eletric_oven",
      default_watts: 4500,
      max_select_range: 5,
      flag_residents: false,
    },
    {
      category_id: 1,
      name: "Micro-ondas",
      photo: "microondas.png",
      input_name: "microwave",
      default_watts: 2000,
      max_select_range: 10,
      flag_residents: true,
    },
    {
      category_id: 2,
      name: "Máquina de lavar roupa",
      photo: "maquina_lavar_roupa.png",
      input_name: "washing_machine",
      default_watts: 1000,
      max_select_range: 5,
      flag_residents: false,
    },
    {
      category_id: 2,
      name: "Secadora de roupas",
      photo: "secadora_roupa.png",
      input_name: "clothes_dryer",
      default_watts: 3500,
      max_select_range: 5,
      flag_residents: false,
    },
    {
      category_id: 3,
      name: "Chuveiro elétrico",
      photo: "chuveiro.png",
      input_name: "shower",
      default_watts: 5500,
      max_select_range: 10,
      flag_residents: true,
    },
    {
      category_id: 3,
      name: "Secador de cabelo",
      photo: "secador_cabelo.png",
      input_name: "hair_dryer",
      default_watts: 1000,
      max_select_range: 10,
      flag_residents: true,
    },
    {
      category_id: 3,
      name: "Torneira elétrica",
      photo: "torneira_eletrica.png",
      input_name: "eletric_faucet",
      default_watts: 2500,
      max_select_range: 10,
      flag_residents: true,
    },
    {
      category_id: 4,
      name: "Ar-condicionado",
      photo: "ar_condicionado.png",
      input_name: "air_conditioner",
      default_watts: 1400,
      max_select_range: 10,
      flag_residents: false,
    },
    {
      category_id: 4,
      name: "Ventilador",
      photo: "ventilador.png",
      input_name: "fan",
      default_watts: 100,
      max_select_range: 20,
      flag_residents: false,
    },
    {
      category_id: 4,
      name: "Aspirador de pó",
      photo: "aspirador_po.png",
      input_name: "vacuum_cleaner",
      default_watts: 600,
      max_select_range: 10,
      flag_residents: false,
    },
    {
      category_id: 4,
      name: "Ferro elétrico",
      photo: "ferro_eletrico.png",
      input_name: "eletric_iron",
      default_watts: 1000,
      max_select_range: 10,
      flag_residents: false,
    },
    {
      category_id: 5,
      name: "Videogame",
      photo: "videogame.png",
      input_name: "videogame",
      default_watts: 20,
      max_select_range: 10,
      flag_residents: false,
    },
    {
      category_id: 5,
      name: "Televisão",
      photo: "tv.png",
      input_name: "tv",
      default_watts: 120,
      max_select_range: 10,
      flag_residents: false,
    },
    {
      category_id: 5,
      name: "Computador",
      photo: "pc.png",
      input_name: "computer",
      default_watts: 60,
      max_select_range: 10,
      flag_residents: false,
    },
  ]);
};
